#Author: Balaji N
#Date: 26/09/2022
#Tittle: Airflow PyPi Package Scanning

name: Airflow PyPi Package Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  job1:
    name: Alembic
    runs-on: BNGitHubAgent-01
    permissions: 
      actions: write
      contents: write
      security-events: write
      
    #strategy:
      #fail-fast:  false
      #matrix:
        #language: ['python']

    steps:
    - name:  Checkout Respository
      uses: actions/checkout@v2

    - name: Curl Download Alembic PyPI Repo
      #working-directory: /temp
      run: |
        curl -L -O https://files.pythonhosted.org/packages/2a/78/19c9330d91ea9842c974d01b7e68b8ab0de4429fee371edeb207f4af4151/alembic-1.5.8.tar.gz
        tar -xvf alembic-1.5.8.tar.gz -C /github/workspace

    - name: Run Snyk to Check
      uses: snyk/actions/python-3.6@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Upload a Build Artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: alembic
        path: |
          alembic-1.5.8/*
          "!alembic-1.5.8.tar.gz"
          "!.github"
          "!.git"
        if-no-file-found: error
        retention-days: 1
      
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: alembic

    - name: Zipping the Artifact for Release
      uses: thedoctor0/zip-release@master
      with:
        filename: alembic-1.5.8.zip

    - name: Creating Release
      id: bn_alembic
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: alembic-1.5.8-V${{ github.run_number }}
        release_name: Release alembic-1.5.8-V${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      id: bn_upload_artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.bn_alembic.outputs.upload_url }}
        asset_path: ./alembic-1.5.8.zip
        asset_name: alembic-1.5.8-V${{ github.run_number }}.zip
        asset_content_type: application/zip

  job2:
    #if: ${{ alaways() }}
    #needs: [job1]
    name: AMQP PyPI Scanning
    runs-on: BNGitHubAgent-01
    permissions:
      actions: write
      contents: write
      security-events: write

    #strategy:
      #fail-fast: false
      #matrix:
        #language: ['python']
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Curl Download AMQP PyPI
      run: |
        curl -L -O https://files.pythonhosted.org/packages/37/9f/d54494a157d0dcd1673fe7a1bcce7ac70d3eb6d5d6149749450c87a2c959/amqp-2.6.1.tar.gz
        tar -xvf amqp-2.6.1.tar.gz

    - name: Run Snyk Checking
      uses: snyk/actions/python-3.6@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: amqp
        path: |
          amqp-2.6.1/*
          !amqp-2.6.1.tar.gz
          !.githun
          !.git
        if-no-file-found: error
        retention-days: 1

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: amqp

    - name:  Zipping AMQP PyPI
      uses: thedoctor0/zip-release@master
      with:
        filename: amqp-2.6.1.zip
      
    - name: Create Release
      id: bn_amqp
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: amqp-2.6.1-V${{ github.run_number }}
        release_name: Release amqp-2.6.1-V${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload AMQP Release Artifact
      id: bn-upload-artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.bn_amqp.outputs.upload_url }}
        asset_path: ./amqp-2.6.1.zip
        asset_name: amqp-2.6.1-V${{ github.run_number }}.zip
        asset_content_type: application/zip
