name: Python Package Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  job1:
    name: CodeQL Scanning
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['python']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with: 
        languages: ${{ matrix.language }}
    
    - name: AutoBuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  job2:
    name: Snyk Code Scanning
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Checout Repository
      uses: action/checkout@v2

    - name: Run Snyk to Check for Vulerabilities
      uses: snyk/actions/python-3.8@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-out=snyk.sarif

    - name: Upload Result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      continue-on-error: true
      with:
        sarif_file: snyk.sarif

  job3:
    name: Publish Artifact
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [job1, job2]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Upload a Build Artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: BNTEST Package
        path: |
          BNTEST
          setup.py
        if-no-file-found: error
        retention-days: 1

  job4:
    name: Relaseing the Assest
    runs-on: ubuntu-latest
    needs: job3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: BNTEST Package

    - name: Build Project
      run: |
        zip --junk-paths BNTEST Package
    
    - name: Create Release
      id: bntest_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Relase ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: bntest-upload-assest
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.bntest_release.output.upload_url }}
        assest_path: ./bntest-package.zip
        assest_name: bntest-package.zip
        assest_content_type: application/zip
