name: PyPi Package Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  job1:
    name: Snyk Code Scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Curl Download PyPI
      run: |
        curl -L -O https://files.pythonhosted.org/packages/af/e8/894c71e914dfbe01276a42dfad40025cd96119f2eefc39c554b6e8b9df86/setuptools-60.10.0.tar.gz
        tar -xvf setuptools-60.10.0.tar.gz

    - name: Run Snyk to Check for Vulerabilities
      uses: synk/actions/python-3@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --sarif-file-out=snyk.sarif
    
    - name: Upload Result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      continue-on-error: true
      with:
        sarif_file: snyk.sarif      
